spring:
  application:
    name: "ConfigServer"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "git@github.com:AravindNaani/ecomm-data.git"
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
    port: 8091